### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by jimblue** [mblode/vscode-twig-language#3]
The twig formatting make some strange things.
It add a lot of line break where it shouldn't and mess up the reading and sometime the output.
For exemple this:

```twig
<button>{{ "THEME_SHARE.SHAREON"|t }}facebook</button>
```
format into this:
```twig
<button>{{ "THEME_SHARE.SHAREON"|t }}
        facebook</button>
```

Is it possible to correct it or to have an option to choose how should Twig format (only tab or tab + line break)

Thank you so much

**Comment by mblode** [comment]
Yeah there are a bunch of options that Pretty Diff excepts and I need to create the ability to edit the formatting in User Settings. Right now it is 100% opinionated and I need to change that to allow some more flexibility

**Comment by jimblue** [comment]
Yep seems important to let your plugin adapt each dev workflow :)

**Comment by jimblue** [comment]
I don't know if I should open a knew issue because it's a adjacent problem of formatting:

This:

```twig
 {% set count = search_results ? search_results.count : 0 %}
```

format into this:

```twig
{% set count = search_results
          ? search_results.count
          : 0 %}
```

Doesn't help readibility

**Comment by jimblue** [comment]
Even this:

```twig
{% set page_image = page.media.images|first.cropZoom(750, 750) %}
```

format into this:

```twig
{% set page_image = page.media.images | first.cropZoom(750, 750) %}
```

And this time this break the official language formatting...

**Comment by mblode** [comment]
Interesting, I think this might be an issue regarding the chained methods option in PrettyDiff. I'm going to release a version today that had it set to none by default and I'm working on giving you the options to change the settings.

I will try test it on http://prettydiff.com and make all the settings match the current extension options:
```
        lang: 'twig',
        mode: 'beautify',
        insize: options.tabSize,
        newline: true,
        objsort: 'none',
        wrap: 0,
        methodchain: 'chain',
        bracepadding: false,
        space: false,
        endcomma: false
```

Then experiment making adjustments to the options that could fix the issue. But right now I don't have my laptop...

**Comment by mblode** [comment]
I have fixed these issues with formatting, however, the only thing I need to fix is that it automatically adds a space between a filter: `{% set page_image = page.media.images | first.cropZoom(750, 750) %}`

**Comment by jimblue** [comment]
Hey thanks for this update that resolve almost every problem I had.
As you said only the added space between filter bug remain unsolved.

**Comment by mblode** [comment]
Awesome! I think I will get in contact with the guy from pretty diff and just query him about the remaining issues that I have with Twig formatting.

**Comment by jimblue** [comment]
Yes that's probably a good idea.
You should also talking about the following, I had the same kind of issue with html code this time:

<img width="282" alt="screen shot 2017-11-25 at 23 28 49" src="https://user-images.githubusercontent.com/10623367/33235439-c6d82272-d238-11e7-9dfb-768326b701f0.png">
<img width="273" alt="screen shot 2017-11-25 at 23 28 57" src="https://user-images.githubusercontent.com/10623367/33235440-c6f624ac-d238-11e7-982e-793b67f824af.png">

**Comment by mblode** [comment]
Fixed inline Twig/HTML boundary handling in 0.10.0 and added regression tests.
